### ISSUE TITLE
Change css by sass

### ISSUE THREAD

**Issue by nmontesdeoca** [nmontesdeoca/cargas-client#55]
We should use sass instead of plain css. Delete our style.css, remove the call from the index.html and start to use sass.

**Comment by neggro** [comment]
I think we are already using sass, please confirm.

**Comment by nmontesdeoca** [comment]
Yes, but I think we need to create new classes instead of overwriting the
ionic ones. You know.

**Comment by neggro** [comment]
We reviewed this earlier today, there is another open issue related to the css classes
