### ISSUE TITLE
Problems formatting numbers

### ISSUE THREAD

**Issue by nmontesdeoca** [nmontesdeoca/cargas-client#77]
We need to review all the app and identify that problems and fix them. Take a look at "Precio por litro", "Distancia", etc.

![captura de pantalla 2014-10-25 a las 13 38 44](https://cloud.githubusercontent.com/assets/993840/4780201/4aa267d4-5c5d-11e4-81ca-5b6d49b7ad4f.png)

**Comment by neggro** [comment]
Nico, please confirm, but I think this issue can be closed since you are using "angular-dynamic-locale" library, I guess using this library fix this issue.

**Comment by nmontesdeoca** [comment]
I think you are rigth and we can close this issue.
